### DISCUSSION TITLE
mqtt not working?

### DISCUSSION THREAD

**Discussion by zerog2k** [jaredmauch/eg4-bridge#10] [General]
I can't seem to get mqtt to publish

I see things in the log like
```
[2025-06-11T01:04:26.522 WARN eg4_bridge::mqtt] ignoring Invalid ReadInput block: Register 0 is valid, but received incorrect length - received length=160, expected between 2 and 80 bytes or 254. Each input block should start at a multiple of 40 up to 200.
[2025-06-11T01:04:26.522 ERROR eg4_bridge::coordinator] Failed to send data to MQTT: channel closed
```

publishing to InfluxDB works fine, and mqtt publishing works fine w/ lxp-bridge 

config section is
```
# MQTT configuration
mqtt:
  enabled: true
  host: mqtt.lan
  port: 1883
  username: '' 
  password: ''
  topic: eg4/#
```
